
ifneq ($(CI), true)
LOCAL_ARG = --local --verbose --diagnostics
endif

ifeq ($(INSPECT), true)
INSPECT = --inspect --inspect-brk
endif

update-contracts:
	@echo 'Updating src/contracts.ts'
	@echo '// this file is autogenerated from https://contracts.decentraland.org/addresses.json, do not edit manually' > src/contracts.ts
	@echo 'export = (' >> src/contracts.ts
	@curl -s https://contracts.decentraland.org/addresses.json >> src/contracts.ts
	@echo ') as Record<string, Record<string, string>>' >> src/contracts.ts

	@echo 'Updating src/collections-v1.ts'
	@echo '// this file is autogenerated, do not edit manually' > src/collections-v1.ts
	@echo 'export =' > src/collections-v1.ts
	@curl \
		-X POST \
		-H "Content-Type: application/json" \
		--data '{ "query": "{collections {id,name,symbol,isApproved,isCompleted}}"}' \
		-s https://subgraph.decentraland.org/collections-ethereum-mainnet | jq '.data.collections' >> src/collections-v1.ts

build: update-contracts
	@echo 'Compiling TypeScript...'
	@./node_modules/.bin/tsc -p tsconfig.json
	@rm -rf node_modules/@microsoft/api-extractor/node_modules/typescript || true
	@echo 'Analyzing generated types...'
	@./node_modules/.bin/api-extractor run $(LOCAL_ARG) --typescript-compiler-folder ./node_modules/typescript

test:
	export TS_NODE_PROJECT='./test/tsconfig.json'; node $(INSPECT) --require ts-node/register --async-stack-traces --experimental-modules node_modules/.bin/_mocha --timeout 10000 --reporter spec

ci: | build test

.PHONY: build test
